workspace:
  base: /go
  path: src/github.com/belak/go-ping

pipeline:
  deps:
    image: golang:1.10
    commands:
      - go get -t ./...

  test:
    group: test
    image: golang:1.10
    commands:
      - go test -v ./...

  lint:
    group: test
    image: golang:1.10
    commands:
      - go get github.com/alecthomas/gometalinter
      - gometalinter --install
      - gometalinter ./...

  build:
    group: test
    image: golang:1.10
    commands:
      - go build -race -o ping_linux ./cmd/ping/ping.go
      - ./ping_linux --privileged -c 2 www.google.com
      - ./ping_linux --privileged -c 3 -i 200ms www.google.com
      - ./ping_linux --privileged -c 10 -i 100ms -t 1s www.google.com
      - GOOS=darwin go build -o ping_darwin ./cmd/ping/ping.go
