language: go
go:
  - "1.10"
  - stable

before_install:
  - go get -u github.com/alecthomas/gometalinter
  - $HOME/gopath/bin/gometalinter --install

script:
  # Run tests
  - go test -v ./...

  # Run linting
  # NOTE: This is currently disabled because for whatever reason gosec has a
  # false positive and I'm not 100* sure how to handle it.
  #- $HOME/gopath/bin/gometalinter ./...

  # Build the project and attempt to run some pings we expect to succeed
  - go build -race -o ping_linux ./cmd/ping/ping.go
  - sudo ./ping_linux --privileged -c 2 www.google.com
  - sudo ./ping_linux --privileged -c 3 -i 200ms www.google.com
  - sudo ./ping_linux --privileged -c 10 -i 100ms -t 1s www.google.com

   # Ensure this builds on macOS as well
  - GOOS=darwin go build -o ping_darwin ./cmd/ping/ping.go
